### ISSUE TITLE
Please add support for iOS and iPadOS Safari browser

### ISSUE THREAD

**Issue by Emasoft** [HL-Bo/user-script#1]
Thank you for the awesome "Remove Restrictions and Restore Default Behavior" userscript! 👍🫡

I have some humble requests for improvements of the userscript:

 - The script doesn't work on mobile Safari (iOS iPhone and iPadOS iPad). The web pages hang in the middle of loading, becoming unresponsive. (I'm using the "Stay" Safari Extension as userscript manager);
 - There is no 'right click' contextual Menu on iOS/iPadOS Safari. Many options are only available after selecting things and pressing the right click button of the mouse. But there is no mouse on mobile browsers. Can you add a floating touch button to open the contextual right click menu?
 - There are no ALT or CTRL keys in the iOS/iPadOS Safari virtual keyboard, and also there are no ESC key, no PageUP key, no PageDOWN key, no END key, no HOME key, and most of none of the 4 ARROWS KEYS. This prevents one from using VSCode web on iPhone/iPad. Can you add those keys as floating buttons, maybe with some common shortcuts too?
 Here is the list of the most common shortcuts (they are from VSCode, but they should work on other web apps too):
 
 
[keyboard-shortcuts-linux.pdf](https://github.com/HL-Bo/user-script/files/15265084/keyboard-shortcuts-linux.pdf)
[keyboard-shortcuts-windows.pdf](https://github.com/HL-Bo/user-script/files/15265087/keyboard-shortcuts-windows.pdf)
[keyboard-shortcuts-macos.pdf](https://github.com/HL-Bo/user-script/files/15265088/keyboard-shortcuts-macos.pdf)

Thanks in advance! 🙏🥹

**Comment by HL-Bo** [comment]
Hello, I have understood your questions and needs.

Since I don't have an iOS device, this script has not been tested on Safari. Thanks for the feedback, I'll try to fix this.

Considering that this script affects many of the vscode.dev's useful behaviors, this script excludes vscode.dev by default. At the same time, because this script is designed to remove the anti-copy and anti-debugging functions of the web page, this script will not add the functions related to virtual buttons. I'll try to write a new script to accomplish this feature, though.

*The above (including this sentence) was translated by Bing, and below is its original text.*

你好，我已了解到你的问题和需求。

由于我没有iOS设备，所以这个脚本未曾在Safari上测试。感谢你的反馈，我将尝试解决此问题。

考虑到此脚本会影响vscode.dev的许多有用的行为，所以此脚本默认排除了vscode.dev。同时因为此脚本旨在移除网页的反复制、反调试功能，所以此脚本将不会添加虚拟按键的相关功能。不过，我将尝试写一个新的脚本以完成此功能。

**Comment by HL-Bo** [comment]
# Tasks

- [ ] `remove-limits`: Check and resolve compatibility issues with Safari.
- [ ] New script: `virtual-operations`.
- [ ] `virtual-operations`: virtual right mouse button.
- [ ] `virtual-operations`: virtual keys and shortcuts.

**Comment by Emasoft** [comment]
> Hello, I have understood your questions and needs.
> I'll try to write a new script to accomplish this feature, though.

Thank you very much! ☺️👍
I will test it as soon as you add the features, and I'll give you some feedback.
